// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef gui2_h
#define gui2_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Dial.H>
extern void updateTheta(Fl_Dial*, void*);
extern Fl_Dial *thetaD;
#include <FL/Fl_Roller.H>
extern void updateAlpha(Fl_Roller*, void*);
extern Fl_Roller *alphaR;
extern void updateMu(Fl_Roller*, void*);
extern Fl_Roller *muR;
#include <FL/Fl_Check_Button.H>
extern void EnableQuantize(Fl_Check_Button*, void*);
#include <FL/Fl_Value_Input.H>
extern void updateNumQColors(Fl_Value_Input*, void*);
extern Fl_Value_Input *numQColorsV;
#include <FL/Fl_Button.H>
extern void run_c2g_callback(Fl_Button*, void*);
extern void updateAlphaV(Fl_Value_Input*, void*);
extern Fl_Value_Input *alphaV;
extern void updateMuV(Fl_Value_Input*, void*);
extern Fl_Value_Input *muV;
extern void updateThetaV(Fl_Value_Input*, void*);
extern Fl_Value_Input *thetaV;
extern void LoadSource(Fl_Button*, void*);
extern void run_c2g_thetaCircle(Fl_Button*, void*);
extern void quit_cb(Fl_Button*, void*);
Fl_Double_Window* make_ctrl_window();
#endif
