// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "scrollW.h"

Fl_Double_Window* make_scroll_window() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(341, 320);
    w = o;
    { Fl_Scroll* o = new Fl_Scroll(13, 12, 320, 290);
      o->end();
      Fl_Group::current()->resizable(o);
    }
    o->end();
  }
  return w;
}
