// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef scrollW_h
#define scrollW_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Scroll.H>
Fl_Double_Window* make_scroll_window();
#endif
