// generated by Fast Light User Interface Designer (fluid) version 1.0106

#include "thetacircle2.h"
#include "color2gray.h"
extern Color2GrayIt *c2gTC;
extern int unitc,ww,wh;
#define MAX(a,b) a < b ? b : a
extern void fillBoxWithImage(Fl_Box *box, int i, char *name, Color2GrayIt *Lc2g);

Fl_Group *Box_Group=(Fl_Group *)0;

Fl_Box *Box_0=(Fl_Box *)0;

Fl_Box *Box_45=(Fl_Box *)0;

Fl_Box *Box_90=(Fl_Box *)0;

Fl_Box *Box_135=(Fl_Box *)0;

Fl_Box *Box_180=(Fl_Box *)0;

Fl_Box *Box_225=(Fl_Box *)0;

Fl_Box *Box_270=(Fl_Box *)0;

Fl_Box *Box_315=(Fl_Box *)0;

Fl_Box *Box_Original=(Fl_Box *)0;

Fl_Box *Box_OldGray=(Fl_Box *)0;

Fl_Double_Window* thetaCircleWindow() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = new Fl_Double_Window(1019, 852, "Color2Gray over Values of Theta");
    w = o;
    o->box(FL_EMBOSSED_BOX);
    o->color((Fl_Color)55);
    o->labelfont(8);
    { Fl_Group* o = Box_Group = new Fl_Group(0, 0, 974, 940);
      { Fl_Box* o = Box_0 = new Fl_Box(774, 289, 200, 206, "0");
        o->user_data((void*)(0));
        char Tname[256]; c2gTC->getImageName(0,Tname);
        fillBoxWithImage(Box_0, I0, Tname,c2gTC);
      }
      { Fl_Box* o = Box_45 = new Fl_Box(699, 75, 200, 200, "45");
        o->user_data((void*)(45));
        char Tname[256]; c2gTC->getImageName(45, Tname);
        fillBoxWithImage(Box_45, I45, Tname,c2gTC);
      }
      { Fl_Box* o = Box_90 = new Fl_Box(482, 10, 200, 200, "90");
        o->user_data((void*)(90));
        char Tname[256]; c2gTC->getImageName(90,Tname);
        fillBoxWithImage(Box_90, I90, Tname,c2gTC);
      }
      { Fl_Box* o = Box_135 = new Fl_Box(264, 75, 200, 200, "135");
        o->user_data((void*)(135));
        char Tname[256]; c2gTC->getImageName(135,Tname);
        fillBoxWithImage(Box_135, I135, Tname,c2gTC);
      }
      { Fl_Box* o = Box_180 = new Fl_Box(204, 292, 200, 200, "180");
        o->user_data((void*)(180));
        char Tname[256]; c2gTC->getImageName(180,Tname);
        fillBoxWithImage(Box_180, I180, Tname,c2gTC);
      }
      { Fl_Box* o = Box_225 = new Fl_Box(264, 510, 200, 200, "225");
        o->user_data((void*)(225));
        char Tname[256]; c2gTC->getImageName(225,Tname);
        fillBoxWithImage(Box_225, I225, Tname,c2gTC);
      }
      { Fl_Box* o = Box_270 = new Fl_Box(482, 585, 200, 200, "270");
        o->user_data((void*)(270));
        char Tname[256]; c2gTC->getImageName(270,Tname);
        fillBoxWithImage(Box_270, I270, Tname,c2gTC);
      }
      { Fl_Box* o = Box_315 = new Fl_Box(699, 510, 200, 200, "315");
        o->user_data((void*)(315));
        char Tname[256]; c2gTC->getImageName(315,Tname);
        fillBoxWithImage(Box_315, I315, Tname,c2gTC);
      }
      { Fl_Box* o = Box_Original = new Fl_Box(482, 292, 200, 200, "Original");
        o->user_data((void*)(-1));
        char Tname[256]; c2gTC->getImageName(-1,Tname);
        fillBoxWithImage(Box_Original, IO, Tname,c2gTC);
      }
      { Fl_Box* o = Box_OldGray = new Fl_Box(15, 645, 200, 200, "Gray");
        o->user_data((void*)(-2));
        char Tname[256];c2gTC->getImageName(-2,Tname);
        fillBoxWithImage(Box_OldGray, IOG, Tname,c2gTC);
      }
      o->end();
    }
    o->end();
    o->resizable(o);
  }
  return w;
}
