// generated by Fast Light User Interface Designer (fluid) version 1.0106

#ifndef thetacircle2_h
#define thetacircle2_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
extern Fl_Group *Box_Group;
#include <FL/Fl_Box.H>
extern Fl_Box *Box_0;
extern Fl_Box *Box_45;
extern Fl_Box *Box_90;
extern Fl_Box *Box_135;
extern Fl_Box *Box_180;
extern Fl_Box *Box_225;
extern Fl_Box *Box_270;
extern Fl_Box *Box_315;
extern Fl_Box *Box_Original;
extern Fl_Box *Box_OldGray;
Fl_Double_Window* thetaCircleWindow();
#endif
